name: haskell-src-exts-observe
version: 0.1.0
synopsis: Observable orphan instances for haskell-src-exts
homepage:            https://github.com/pepeiborra/haskell-src-exts-observe
license:             BSD3
author:              Jose Iborra
maintainer:          pepeiborra@gmail.com
copyright:           All Rights Reserved
category:            language
extra-source-files:
- README.md

library: 
  source-dirs: src
  dependencies:
    - base
    - haskell-src-exts
    - Hoed
